### ISSUE TITLE
CARLA 0.9.10 compatibility?

### ISSUE THREAD

**Issue by tomov** [OATML/carsuite#18]
Hi, great repo! Wondering of it's compatible with the latest Carla? Getting some segfaults:

```(conanenvpython) (prediction) momchiltomov@BOS-R90ZS9FK:~/carla/oatomobile$ python test.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=118144 LargeMemoryPoolOffset=249280
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=105648 LargeMemoryPoolOffset=236784
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)


4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=118144 LargeMemoryPoolOffset=249280
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=105648 LargeMemoryPoolOffset=236784
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=118144 LargeMemoryPoolOffset=249280
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119
Malloc Size=105648 LargeMemoryPoolOffset=236784
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
```

Thanks!

**Comment by jwang078** [comment]
Hello, were you able to find a solution for this?

**Comment by tomov** [comment]
Thanks for checking in, we actually ended up implementing a similar framework on our end

Momchil Tomov

**Comment by Morphlng** [comment]
> Hello, were you able to find a solution for this?

I've done some changes to make this Environment compatible with Carla 0.9.13 (hopefully 0.9.10+), maybe you can check out my [fork repo](https://github.com/Morphlng/oatomobile)

**Comment by chungcode0218** [comment]
@Morphlng 
Hello, sir. I am currently encountering a dependency conflict when attempting to use OAtomobile alongside other packages, particularly TensorFlow. Here are the version constraints and conflicts I've come across:

OAtomobile requires:

absl-py==0.9.0
numpy==1.19.5
pandas==0.25.3
scipy==1.4.1
...other dependencies...
TensorFlow 2.13.1 requires:

absl-py>=1.0.0 (conflicts with OAtomobile's requirement for absl-py==0.9.0)
numpy<=1.24.3,>=1.22 (conflicts with OAtomobile's requirement for numpy==1.19.5)
Open3D 0.18.0 requires:

pandas>=1.0 (conflicts with OAtomobile's requirement for pandas==0.25.3)
Scikit-learn 1.3.2 requires:

scipy>=1.5.0 (conflicts with OAtomobile's requirement for scipy==1.4.1)
I understand that resolving dependency issues can be complex, especially with libraries that have specific version requirements. I am seeking advice on how to manage or resolve these conflicts. Is there a recommended set of compatible versions of these libraries that can work with OAtomobile? Or is there an update planned for OAtomobile that might alleviate these conflicts?

Any guidance or suggestions you can provide would be greatly appreciated as I aim to utilize OAtomobile for my project.

Thank you for your time and assistance.

Best regards

**Comment by Morphlng** [comment]
> OAtomobile requires:
> 
> absl-py==0.9.0 numpy==1.19.5 pandas==0.25.3 scipy==1.4.1 ...other dependencies... 

@chungcode0218 Have you tried to loosen up these requirements in oatomobile. I.e., delete the specific version requires, install TF2 first and then oatomobile? I haven't been using this project ever since we've started to build our own env. But as far as I'm concerned, the environment is not using any particular feature that requires you to maintain these conflicting libraries as their original specified version.

**Comment by chungcode0218** [comment]
@Morphlng 

Thank you for your prompt response and helpful suggestions. I will try loosening the version constraints and installing TensorFlow first as you recommended. Appreciate your guidance on this!

Best regards

**Comment by 942411526** [comment]
> > OAtomobile requires:
> > absl-py==0.9.0 numpy==1.19.5 pandas==0.25.3 scipy==1.4.1 ...other dependencies...
> 
> @chungcode0218 Have you tried to loosen up these requirements in Oatomobile. I.e., delete the specific version requires, install TF2 first and then oatomobile? I haven't been using this project ever since we've started to build our own env. But as far as I'm concerned, the environment is not using any particular feature that requires you to maintain these conflicting libraries as their original specified version.



> > Hello, were you able to find a solution for this?
> 
> I've done some changes to make this Environment compatible with Carla 0.9.13 (hopefully 0.9.10+), maybe you can check out my [fork repo](https://github.com/Morphlng/oatomobile)

Thanks for your work,but there some problems in 0.9.10 
Hello from the pygame community. https://www.pygame.org/contribute.html
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=118144 LargeMemoryPoolOffset=249280 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=118144 LargeMemoryPoolOffset=249280 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=118144 LargeMemoryPoolOffset=249280 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=118144 LargeMemoryPoolOffset=249280 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=118144 LargeMemoryPoolOffset=249280 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

**Comment by 942411526** [comment]
> > Hello, were you able to find a solution for this?
> 
> I've done some changes to make this Environment compatible with Carla 0.9.13 (hopefully 0.9.10+), maybe you can check out my [fork repo](https://github.com/Morphlng/oatomobile)

thanks for your work ,but there are some problem  when i run the code  
/home/yx/anaconda3/envs/carla_ros/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    observation = environment.reset()
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/core/rl.py", line 67, in reset
    return self.simulator.reset(*args, **kwargs)
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/simulators/carla/simulator.py", line 1748, in reset
    obs = self.step(action=None)
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/simulators/carla/simulator.py", line 1780, in step
    timeout=defaults.QUEUE_TIMEOUT,
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/core/simulator.py", line 120, in get_observations
    return Observations(self.sensors, *args, **kwargs)
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/core/simulator.py", line 82, in __init__
    for uuid, sensor in sensors.items()]
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/core/simulator.py", line 82, in <listcomp>
    for uuid, sensor in sensors.items()]
  File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/simulators/carla/simulator.py", line 1290, in get_observation
    destination=end_waypoint.transform.location,
  **File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/util/carla.py", line 735, in global_plan
    grp = GlobalRoutePlanner(wmap=world.get_map(), sampling_resolution=1)
TypeError: __init__() got an unexpected keyword argument 'wmap'**

**Comment by Morphlng** [comment]
> **File "/home/yx/oatomobile-alpha/oatomobile-alpha/oatomobile/util/carla.py", line 735, in global_plan
grp = GlobalRoutePlanner(wmap=world.get_map(), sampling_resolution=1)
TypeError: init() got an unexpected keyword argument 'wmap'**

@942411526 Hi!

This error happened because since Carla 0.9.12, GlobalRoutePlanner's API has changed.

Originally, you would have to first instantiate a `GlobalRoutePlannerDAO`, that takes argument `wmap` and `sampling_resolution`. Then pass it to `GlobalRoutePlanner`. From 0.9.12, there is no `GlobalRoutePlannerDAO` anymore, and you should directly instantiate `GlobalRoutePlanner(wmap, sampling_resolution)`.

Because my fork was targetting version 0.9.13, this kind of unmatched api can happened.
